---
name: Format Check
on:
  push:
    branches:
      - main
      - /^release-.*$/
    tags: ["*"]
    paths:
      - "**/*.jl"
      - ".github/workflows/style.yml"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**/*.jl"
      - ".github/workflows/style.yml"
jobs:
  format-check:
    name: Julia
    # These permissions are needed to:
    # - Delete old caches: https://github.com/julia-actions/cache#usage
    # - Post formatting suggestions: https://github.com/reviewdog/action-suggester#required-permissions
    permissions:
      actions: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        with:
          version: "1"
      - uses: julia-actions/cache@b7788abd52452d5bc033d69796e110d9906af4ab # v3.2.0
      - name: Install JuliaFormatter
        shell: julia --project=@format --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(; name="JuliaFormatter", version="1"))
      - name: Check formatting
        shell: julia --project=@format --color=yes {0}
        run: |
          using JuliaFormatter
          format("."; verbose=true) || exit(1)
      # Add formatting suggestions to non-draft PRs even if when "Check formatting" fails
      - uses: reviewdog/action-suggester@2558ba17e65a9039e73764a73009fc05fef28a46 # v1.24.3
        if: ${{ !cancelled() && github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
        with:
          tool_name: JuliaFormatter
